"""Reset models to singular with cascade

Revision ID: b3ff89837011
Revises: 
Create Date: 2025-12-22 14:13:41.817813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ff89837011'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antenna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('hbeamwidth', sa.Float(), nullable=False),
    sa.Column('vbeamwidth', sa.Float(), nullable=False),
    sa.Column('gain', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.String(length=100), nullable=False),
    sa.Column('cell_code', sa.String(length=50), nullable=False),
    sa.Column('antenna_tech', sa.String(length=50), nullable=False),
    sa.Column('band', sa.String(length=50), nullable=False),
    sa.Column('sector_code', sa.String(length=50), nullable=False),
    sa.Column('technology', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_id')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wilaya',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('commune',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('wilaya_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wilaya_id'], ['wilaya.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_site', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('support_nature', sa.String(length=50), nullable=True),
    sa.Column('support_type', sa.String(length=50), nullable=True),
    sa.Column('support_height', sa.Float(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('commune_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commune_id'], ['commune.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_site')
    )
    op.create_table('sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_sector', sa.String(length=80), nullable=False),
    sa.Column('azimuth', sa.Integer(), nullable=False),
    sa.Column('hba', sa.Integer(), nullable=False),
    sa.Column('coverage_goal', sa.String(length=50), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_sector')
    )
    op.create_table('cell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cellname', sa.String(length=150), nullable=False),
    sa.Column('technology', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('antenna_tech', sa.String(length=50), nullable=True),
    sa.Column('tilt_mechanical', sa.Float(), nullable=True),
    sa.Column('tilt_electrical', sa.Float(), nullable=True),
    sa.Column('antenna_id', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['antenna_id'], ['antenna.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cellname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cell')
    op.drop_table('sector')
    op.drop_table('site')
    op.drop_table('commune')
    op.drop_table('wilaya')
    op.drop_table('supplier')
    op.drop_table('region')
    op.drop_table('mapping')
    op.drop_table('antenna')
    # ### end Alembic commands ###
